services:

    auth.event.refresh_token_listener:
        class: AuthBundle\EventListener\RefreshTokenListener
        arguments: [ @auth.services.jwt_refresh_manager ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    auth.services.jwt_refresh_manager:
        class: AuthBundle\Services\JwtRefreshManager
        arguments: [ @lexik_jwt_authentication.encoder, @doctrine_cache.providers.jwt_refresh_token ]
