security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: password, roles: [ 'ROLE_USER' ] }
                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error))/
            security: false

        refreshtoken:
            pattern:  ^/refresh_token$
            stateless: true
            security: false

        gettoken:
            pattern:  ^/get_token$
            stateless: true
            gfreeau_get_jwt:
                # this is the default config
                username_parameter: username
                password_parameter: password
                post_only: true
                authentication_provider: security.authentication.provider.dao
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: false
                    name:    bearer

    access_control:
        - { path: ^/,      roles: IS_AUTHENTICATED_FULLY }
