security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: password, roles: [ 'ROLE_USER' ] }
                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error))/
            security: false

        refreshtoken:
            pattern:  ^/refresh_token$
            stateless: true
            security: false

        gettoken:
            pattern:  ^/get_token$
            stateless: true
            get_jwt: ~

        app:
            pattern:   ^/
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: false
                    name:    bearer

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
